### PR TITLE
Updated tsify to version 0.5.6

### LINKED ISSUE #1744: Update to tsify 0.5.5 or higher
### Describe the improvement you'd like to request

Due to a build error when updating from tsify 0.4.5 to 0.5.5 we are currently stuck on this older version (see #1745 for PR adding ignore conditions to dependabot). We should figure out this build error and update, or else update if a future version of tsify resolves this on their end.

The build error is 

```
 error[E0229]: associated item constraints are not allowed here
   --> cedar-policy-core/src/entities/json/value.rs:929:24
    |
929 | pub enum EntityUidJson<Context = NoStaticContext> {
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^ associated item constraint not allowed here
    |
help: to use `NoStaticContext` as a generic argument specify it directly
    |
929 - pub enum EntityUidJson<Context = NoStaticContext> {
929 + pub enum EntityUidJson<NoStaticContext> {
    |
```

occurring on this enum 

https://github.com/cedar-policy/cedar/blob/1bc364953e91110362eaa0fd3465ed6de0a6be9a/cedar-policy-core/src/entities/json/value.rs#L929-L950

See #1719 for dependabot PR demonstrating the error and https://github.com/madonoharu/tsify/issues/67 for a minimal reproducing example. 

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this internal improvement
- [ ] ⚠️ This feature might incur a breaking change

### PR DESCRIPTION
**Pull request by katherine-hough**
## Description of changes
Updated tsify to version 0.5.6 (https://github.com/madonoharu/tsify/issues/67 resolved the issue that preventing us from updating).

## Issue #, if available
Resolves #1744

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [X] A change "invisible" to users (e.g., documentation, changes to "internal" crates like `cedar-policy-core`, `cedar-validator`, etc.)

I confirm that this PR (choose one, and delete the other options):

- [X] Does not update the CHANGELOG because my change does not significantly impact released code.

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [X] Does not require updates because my change does not impact the Cedar formal model or DRT infrastructure.

I confirm that [`docs.cedarpolicy.com`](https://docs.cedarpolicy.com/) (choose one, and delete the other options):

- [X] Does not require updates because my change does not impact the Cedar language specification.

### CODE REVIEW

**Review by chaluli — APPROVED** [review]

**Comment by john-h-kastner-aws** [comment]
Build failure is different but likely related as it's in the wasm build

**Comment by katherine-hough** [comment]
Yeah, it's almost certainly related. I'm hoping to take a closer look today

**Comment by katherine-hough** [comment]
@shaobo-he-aws and I have determined that we will likely need to abort this update.

In commit [3e81856908e8149a856082d194a55ecb402ff7d8](https://github.com/madonoharu/tsify/commit/3e81856908e8149a856082d194a55ecb402ff7d8), the behavior of tsify changed so that type-level serde renames no longer impact the name of corresponding TypeScript type declaration.
The change appears to be intentional to address [issue 43](https://github.com/madonoharu/tsify/issues/43).
We rely on the prior behavior to rename
[cedar_policy_core::est::Policy](https://github.com/cedar-policy/cedar/blob/main/cedar-policy-core/src/est.rs#L57) and [cedar_policy_core::validator::json_schema::Fragment](https://github.com/cedar-policy/cedar/blob/ba7e42c95f895589f0a9216ad1658f104f927d34/cedar-policy-core/src/validator/json_schema.rs#L101).
