### PR TITLE
Upgrade tsify version

### LINKED ISSUE #1744: Update to tsify 0.5.5 or higher
### Describe the improvement you'd like to request

Due to a build error when updating from tsify 0.4.5 to 0.5.5 we are currently stuck on this older version (see #1745 for PR adding ignore conditions to dependabot). We should figure out this build error and update, or else update if a future version of tsify resolves this on their end.

The build error is 

```
 error[E0229]: associated item constraints are not allowed here
   --> cedar-policy-core/src/entities/json/value.rs:929:24
    |
929 | pub enum EntityUidJson<Context = NoStaticContext> {
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^ associated item constraint not allowed here
    |
help: to use `NoStaticContext` as a generic argument specify it directly
    |
929 - pub enum EntityUidJson<Context = NoStaticContext> {
929 + pub enum EntityUidJson<NoStaticContext> {
    |
```

occurring on this enum 

https://github.com/cedar-policy/cedar/blob/1bc364953e91110362eaa0fd3465ed6de0a6be9a/cedar-policy-core/src/entities/json/value.rs#L929-L950

See #1719 for dependabot PR demonstrating the error and https://github.com/madonoharu/tsify/issues/67 for a minimal reproducing example. 

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this internal improvement
- [ ] ⚠️ This feature might incur a breaking change

### PR DESCRIPTION
**Pull request by katherine-hough**
## Description of changes
tsify [released a fix for the renaming issue we encountered back in November](https://github.com/madonoharu/tsify/pull/98) enabling us to upgrade to the latest version using the new `rename` container attribute.

However, the `into_wasm_abi`/`from_wasm_abi`
container attributes which we heavily use are now deprecated because [they can cause memory leaks](https://github.com/madonoharu/tsify#why-are-the-wasm_abi-attributes-deprecated). The recommended alternative is to use the `Ts` wrapper type. To avoid changing the signature of the existing public Rust functions I made new wasm variants. (e.g., `pub fn is_authorized_wasm(call: Ts<AuthorizationCall>) -> Result<Ts<AuthorizationAnswer>, JsError>`).

To check backwards compatibility of the Rust API, I used cargo expand to diff the code for cedar-policy before and after this change. When every feature except tsify, wasm, and wasm-bindgen were enabled there is no difference.
When all features are enabled there are two main differences that are not backwards compatible:
1. There are no longer derived implementations of `OptionFromWasmAbi`, `FromWasmAbi`, `OptionIntoWasmAbi`, `IntoWasmAbi` and `WasmDescribe` for types previously annotated with `#[tsify(into_wasm_abi, from_wasm_abi)]`.
2. The signature of bindgen-generated functions are different
Main:
```rust
            pub unsafe extern "C-unwind" fn __wasm_bindgen_generated_checkParseEntities(
                arg0_1: <<EntitiesParsingCall as wasm_bindgen::convert::FromWasmAbi>::Abi as wasm_bindgen::convert::WasmAbi>::Prim1,
                arg0_2: <<EntitiesParsingCall as wasm_bindgen::convert::FromWasmAbi>::Abi as wasm_bindgen::convert::WasmAbi>::Prim2,
                arg0_3: <<EntitiesParsingCall as wasm_bindgen::convert::FromWasmAbi>::Abi as wasm_bindgen::convert::WasmAbi>::Prim3,
                arg0_4: <<EntitiesParsingCall as wasm_bindgen::convert::FromWasmAbi>::Abi as wasm_bindgen::convert::WasmAbi>::Prim4,
            ) -> wasm_bindgen::convert::WasmRet<
                <CheckParseAnswer as wasm_bindgen::convert::ReturnWasmAbi>::Abi,
            > {  }
}
```

This change:
```rust
        pub unsafe extern "C-unwind" fn __wasm_bindgen_generated_checkParseEntities(
                arg0_1: <<Ts<
                    EntitiesParsingCall,
                > as wasm_bindgen::convert::FromWasmAbi>::Abi as wasm_bindgen::convert::WasmAbi>::Prim1,
                arg0_2: <<Ts<
                    EntitiesParsingCall,
                > as wasm_bindgen::convert::FromWasmAbi>::Abi as wasm_bindgen::convert::WasmAbi>::Prim2,
                arg0_3: <<Ts<
                    EntitiesParsingCall,
                > as wasm_bindgen::convert::FromWasmAbi>::Abi as wasm_bindgen::convert::WasmAbi>::Prim3,
                arg0_4: <<Ts<
                    EntitiesParsingCall,
                > as wasm_bindgen::convert::FromWasmAbi>::Abi as wasm_bindgen::convert::WasmAbi>::Prim4,
            ) -> wasm_bindgen::convert::WasmRet<
                <Result<
                    Ts<CheckParseAnswer>,
                    JsError,
                > as wasm_bindgen::convert::ReturnWasmAbi>::Abi,
            > {  }
```

To check the  backwards compatibility of the TypeScript API, I built the WASM bindings using the "build-wasm.sh" script on this change and main. I manually inspected the diffs. The type definitions and signatures appear to be the same. This is consistent with the tsify documentation which says that the generated TypeScript is unchanged when changing to the `Ts` wrappers.

## Issue #, if available
Resolves: #1744

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [X] A bug fix or other functionality change requiring a patch to `cedar-policy`.

I confirm that this PR (choose one, and delete the other options):

- [X] Updates the "Unreleased" section of the CHANGELOG with a description of my change (required for major/minor version bumps).

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [X] Does not require updates because my change does not impact the Cedar formal model or DRT infrastructure.

I confirm that [`docs.cedarpolicy.com`](https://docs.cedarpolicy.com/) (choose one, and delete the other options):

- [X] Does not require updates because my change does not impact the Cedar language specification.

### CODE REVIEW

**Comment by katherine-hough** [comment]
AFAIK, there is no way to get the coverage check to pass for this PR. We can't write normal tests for the wasm wrapper functions because they take `Ts<T>` parameters. `Ts` is a wrapper around wasm-bindgen's `JsValue` which will panic on targets other than [wasm-32](https://github.com/wasm-bindgen/wasm-bindgen/blob/main/src/lib.rs#L98).

wasm-bindgen has [an experimental test harness](https://wasm-bindgen.github.io/wasm-bindgen/wasm-bindgen-test/index.html) which lets you run Rust tests inside a JavaScript runtime (Node.js or browser) via wasm-pack test. We could use this to sanity test the bindings but I don't know what it would be checking beyond the tests we have in cedar-examples.

File: cedar-policy/src/ffi/convert.rs [hunk 1]
```diff
@@ -151,7 +221,18 @@ pub fn schema_to_text(schema: Schema) -> SchemaToTextAnswer {
...
 /// Return the JSON representation of a schema.
-#[cfg_attr(feature = "wasm", wasm_bindgen(js_name = "schemaToJson"))]
+///
+/// # Errors
+///
+/// Throws if `schema` does not match the `Schema` type, or if the answer cannot
+/// be serialized back to JavaScript.
+#[cfg(feature = "wasm")]
+#[wasm_bindgen(js_name = "schemaToJson")]
+pub fn schema_to_json_wasm(schema: Ts<Schema>) -> Result<Ts<SchemaToJsonAnswer>, JsError> {
```
Comment (victornicolet) [inline cedar-policy/src/ffi/convert.rs:255]: Here, and some other places, we get clippy reporting:
```
warning: this argument is passed by value, but not consumed in the function body
   --> cedar-policy/src/ffi/convert.rs:231:36
    |
231 | pub fn schema_to_json_wasm(schema: Ts<Schema>) -> Result<Ts<SchemaToJsonAnswer>, JsError> {
    |                                    ^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.96.0/index.html#needless_pass_by_value
help: consider taking a reference instead
    |
231 | pub fn schema_to_json_wasm(schema: &Ts<Schema>) -> Result<Ts<SchemaToJsonAnswer>, JsError> {
    |                                    +
```
Which iiuc we should *not fix*, but perhaps suppressing the warning explaining why would prevent accidental breaking fixes.

File: cedar-wasm/CHANGELOG.md [hunk 2]
```diff
@@ -2,6 +2,10 @@
 
 ## Unreleased
 
+### Changed
+
+- Upgraded tsify dependency and migrated wasm bindings to use the new `Ts<T>` wrapper pattern, fixing memory leak. (#2534)
```
Comment (victornicolet) [inline cedar-wasm/CHANGELOG.md]: nit: maybe reword to "fixing memory leak potential when passing malformed inputs"?

**Review by victornicolet — APPROVED** [review]

**Review by lianah — APPROVED** [review]
