### ISSUE TITLE
Update to tsify 0.5.5 or higher

### ISSUE THREAD

**Issue by john-h-kastner-aws** [cedar-policy/cedar#1744]
### Describe the improvement you'd like to request

Due to a build error when updating from tsify 0.4.5 to 0.5.5 we are currently stuck on this older version (see #1745 for PR adding ignore conditions to dependabot). We should figure out this build error and update, or else update if a future version of tsify resolves this on their end.

The build error is 

```
 error[E0229]: associated item constraints are not allowed here
   --> cedar-policy-core/src/entities/json/value.rs:929:24
    |
929 | pub enum EntityUidJson<Context = NoStaticContext> {
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^ associated item constraint not allowed here
    |
help: to use `NoStaticContext` as a generic argument specify it directly
    |
929 - pub enum EntityUidJson<Context = NoStaticContext> {
929 + pub enum EntityUidJson<NoStaticContext> {
    |
```

occurring on this enum 

https://github.com/cedar-policy/cedar/blob/1bc364953e91110362eaa0fd3465ed6de0a6be9a/cedar-policy-core/src/entities/json/value.rs#L929-L950

See #1719 for dependabot PR demonstrating the error and https://github.com/madonoharu/tsify/issues/67 for a minimal reproducing example. 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this internal improvement
- [ ] ⚠️ This feature might incur a breaking change

**Comment by katherine-hough** [comment]
Updating to tsify 0.5.6 also failed. In commit [3e81856908e8149a856082d194a55ecb402ff7d8](https://github.com/madonoharu/tsify/commit/3e81856908e8149a856082d194a55ecb402ff7d8), the behavior of tsify changed so that type-level serde renames no longer impact the name of corresponding TypeScript type declaration.
The change appears to be intentional to address [issue 43](https://github.com/madonoharu/tsify/issues/43).

We rely on the prior behavior to rename
[cedar_policy_core::est::Policy](https://github.com/cedar-policy/cedar/blob/main/cedar-policy-core/src/est.rs#L57) and [cedar_policy_core::validator::json_schema::Fragment](https://github.com/cedar-policy/cedar/blob/ba7e42c95f895589f0a9216ad1658f104f927d34/cedar-policy-core/src/validator/json_schema.rs#L101). As a result, upgrading to tsify 0.5.6 produces the following errors:
```text
pkg/esm/cedar_wasm.d.ts(180,31): error TS2304: Cannot find name 'SchemaJson'.
pkg/esm/cedar_wasm.d.ts(226,33): error TS2304: Cannot find name 'PolicyJson'.
pkg/esm/cedar_wasm.d.ts(231,13): error TS2300: Duplicate identifier 'Policy'.
pkg/esm/cedar_wasm.d.ts(231,31): error TS2304: Cannot find name 'PolicyJson'.
pkg/esm/cedar_wasm.d.ts(535,59): error TS2304: Cannot find name 'PolicyJson'.
pkg/esm/cedar_wasm.d.ts(545,59): error TS2304: Cannot find name 'SchemaJson'.
pkg/esm/cedar_wasm.d.ts(632,18): error TS2300: Duplicate identifier 'Policy'.
```

We will need to monitor the following issue on the tsify repository before upgrading: https://github.com/madonoharu/tsify/issues/70
